version: '3.8'

services:
  book-db:
    container_name: "book-db"
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: book-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./db-volumes/auth-db:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d book-db"]
      interval: 10s
      timeout: 5s
      retries: 5

  liquibase-book-db:
    container_name: "liquibase-book-db"
    image: liquibase/liquibase:4.25
    command: update
    environment:
      LIQUIBASE_COMMAND_DRIVER: org.postgresql.Driver
      LIQUIBASE_COMMAND_URL: jdbc:postgresql://book-db:5432/book-db
      LIQUIBASE_COMMAND_USERNAME: admin
      LIQUIBASE_COMMAND_PASSWORD: admin
      LIQUIBASE_COMMAND_CHANGELOG_FILE: db.changelog.yaml
      LIQUIBASE_SEARCH_PATH: /liquibase/book-db/changelog
    depends_on:
      auth-db:
        condition: service_healthy
    volumes:
      - ./liquibase/book-db/changelog:/liquibase/book-db/changelog
    networks:
      - backend

networks:
  book-network:
    driver: bridge
